# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: MetaZ
email: brian@maven-group.org
description: > # this means to ignore newlines until "baseurl:"
  MetaZ is an mp4 meta-data editor for OS X.  
  It started its life when another great meta-data editor MetaX
  stopped getting updated, some of the web-services it used changed
  in ways that broke functionality and it had some really anoying
  (to us at least) little missing things like no proper window
  resizing. This lead to us starting MetaZ as a reimplementation of
  MetaX with a few ideas of our own sprinkled in there.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://metaz.maven-group.org" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: nibsoar
github_username:  griff

# Build settings
markdown: kramdown

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - scripts/
  - sparkle/
  - vendor/bundle/
  - vendor/bin/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
