#!/bin/sh
set -ev

SRC="$(cd "$(dirname "$0")/.."; pwd -P)"
cd $SRC
curl -o GeoLite2-City.tar.gz -L "https://download.maxmind.com/app/geoip_download?edition_id=GeoLite2-City&license_key=lH0hSvHiqDi9NnpW&suffix=tar.gz"
tar xvf GeoLite2-City.tar.gz --wildcards --strip-components=1 GeoLite2-City_*/GeoLite2-City.mmdb
