name: "Build and deploy"
on:
  push:
  pull_request:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Setup | Checkout
      uses: actions/checkout@v2
    - name: Setup | Ruby
      uses: ruby/setup-ruby@v1
      with:
        working-directory: site
    - name: Setup | Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        target: x86_64-unknown-linux-musl
    - name: Build
      run: "./ci/local"
    - name: Deploy
      uses: nogsantos/scp-deploy@v1.3.0
      if: "github.ref == 'refs/heads/main'"
      with:
        src: target/metazite.tar.gz
        host: xev.maven-group.org
        remote: /opt/metaz.io/metazite.tar.gz
        user: ${{ secrets.SSH_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}